package org.launchcode.aleandelebake.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Entity
public class Contacted {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue
    private int id;

    @NotNull
    @Size(min=3, max=35)
    private String name;

    @NotNull
    @Size(min=1, message = "Email must not be empty")
    private String email;

    @NotNull
    @Size(min = 1, max = 20)
    private String date;

    @NotNull
    @Size(min=1, message = "Message field cannot be empty")
    private String message;

    public Contacted(String email) {
        super();
        this.email=email;
        this.date=date;
        this.message=message;
        this.id=id;
    }

    public Contacted() {

    }

    public int getId() {

        return id;
    }

    public String getEmail() {

        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}