package org.launchcode.aleandelebake.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Entity
public class Msg {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue
    private int id;

    @NotNull
    @Size(min=3, max=30)
    private String name;

    @NotNull
    @Size(min=5, message = "message must not be empty")
    private String msg;

    @NotNull
    @Size(min=8, message = "email must not be empty")
    private String email;

    @NotNull
    @Size(min=8, message = "date must not be empty")
    private String date;

    public Msg(String name, String msg, String email) {
        super();
        this.id = id;
        this.name = name;
        this.msg = msg;
        this.email = email;
        this.date = date;
    }

    public Msg() { }

    public int getId() { return id; }

    public String getName() { return name; }

    public void setName(String name) {
        this.name = name;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String message) { this.msg = msg; }

    public String getEmail() { return email; }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDate() { return date; }

    public void setDate(String date) {
        this.date = date;
    }
}

