package org.launchcode.aleandelebake.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Entity
public class Thankyou {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue
    private int id;

    @NotNull
    @Size(min = 1, max = 30)
    private String name;

    @NotNull
    @Size(min = 1, message = "Email must not be empty")
    private String email;

    @NotNull
    @Size(min = 1, message = "Date must not be empty")
    private String date;

    @NotNull
    @Size(min = 1, message = "Message must not be empty")
    private String message;

    @NotNull
    @Size(min = 1, message = "date must not be empty")
    public Thankyou(String name, String email, String date, String message) {
        super();
        this.id = id;
        this.name = name;
        this.email = email;
        this.date = date;
        this.message = message;

    }

    public Thankyou() {

    }

    public int getId() {

        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {

        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}